PROJECTS = [
    {
        "id": "orchard-at-sarai",
        "title": "Orchard at Sarai",
        "category": "Hospitality · Brand & Growth",
        "year": "2025",
        "cover": "https://images.unsplash.com/photo-1561501900-3701fa6a0864?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "size": "large",
        "order": 1,
        "summary": "A heritage hospitality retreat reimagined for the modern luxury traveller — from positioning to a full digital presence.",
        "services": ["Brand & Growth Marketing", "Social Media Management", "Paid Marketing"],
        "scope": "We repositioned Orchard at Sarai as a serene, design-led escape and built an end-to-end brand and growth engine around it — narrative, visual language, content and performance.",
        "results": [
            {"label": "Direct bookings", "value": "+186%"},
            {"label": "Engagement rate", "value": "7.4%"},
            {"label": "Cost per lead", "value": "-42%"},
        ],
        "gallery": [
            "https://images.unsplash.com/photo-1549294413-26f195200c16?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
            "https://images.unsplash.com/photo-1724947053227-2335bf21d0ae?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
            "https://images.pexels.com/photos/14036444/pexels-photo-14036444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=900&w=1600",
        ],
    },
    {
        "id": "ravissant-india",
        "title": "Ravissant India",
        "category": "Luxury Lifestyle · Social",
        "year": "2025",
        "cover": "https://images.unsplash.com/photo-1585418694458-dc80a5c20294?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "size": "small",
        "order": 2,
        "summary": "Crafting a covetable social-first identity for one of India's most iconic luxury lifestyle houses.",
        "services": ["Social Media Management", "Brand & Growth Marketing"],
        "scope": "We curated an editorial content universe for Ravissant — pairing heritage craftsmanship with contemporary art direction across Instagram and beyond.",
        "results": [
            {"label": "Follower growth", "value": "+58k"},
            {"label": "Avg. reach / reel", "value": "210k"},
            {"label": "Saves uplift", "value": "+312%"},
        ],
        "gallery": [
            "https://images.unsplash.com/photo-1522255272218-7ac5249be344?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
            "https://images.unsplash.com/photo-1528154291023-a6525fabe5b4?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        ],
    },
    {
        "id": "the-aurelia",
        "title": "The Aurelia",
        "category": "Luxury Hotel · Paid Marketing",
        "year": "2024",
        "cover": "https://images.unsplash.com/photo-1724947053227-2335bf21d0ae?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "size": "small",
        "order": 3,
        "summary": "Performance marketing that filled suites at a five-star urban hotel without diluting the brand.",
        "services": ["Paid Marketing", "Website Development"],
        "scope": "A full-funnel paid ecosystem with a refined booking site — built to protect rate integrity while scaling demand.",
        "results": [
            {"label": "ROAS", "value": "11.2x"},
            {"label": "Occupancy", "value": "+27%"},
            {"label": "Booking CVR", "value": "+64%"},
        ],
        "gallery": [
            "https://images.pexels.com/photos/33803734/pexels-photo-33803734.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=900&w=1600",
            "https://images.unsplash.com/photo-1549294413-26f195200c16?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        ],
    },
    {
        "id": "maison-noir",
        "title": "Maison Noir",
        "category": "Fine Dining · Brand",
        "year": "2024",
        "cover": "https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "size": "large",
        "order": 4,
        "summary": "A moody, modern brand world for a chef-led fine dining concept and its launch campaign.",
        "services": ["Brand & Growth Marketing", "Website Development", "Social Media Management"],
        "scope": "From name and identity to the table — we designed a sensorial brand and a sold-out launch across earned, owned and paid.",
        "results": [
            {"label": "Launch waitlist", "value": "3,400"},
            {"label": "Press features", "value": "22"},
            {"label": "First-month covers", "value": "100%"},
        ],
        "gallery": [
            "https://images.unsplash.com/photo-1663530761401-15eefb544889?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
            "https://images.unsplash.com/photo-1585418694458-dc80a5c20294?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        ],
    },
    {
        "id": "assocham",
        "title": "ASSOCHAM",
        "category": "Corporate · Digital & Growth",
        "year": "2024",
        "cover": "https://images.unsplash.com/photo-1488972685288-c3fd157d7c7a?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "size": "small",
        "order": 5,
        "summary": "A modern digital voice for one of India's apex industry bodies and its flagship summits.",
        "services": ["Website Development", "Brand & Growth Marketing", "Social Media Management"],
        "scope": "We modernised the digital presence and amplified flagship events — translating institutional gravitas into a contemporary, shareable format.",
        "results": [
            {"label": "Event registrations", "value": "+2.1x"},
            {"label": "Social reach", "value": "4.8M"},
            {"label": "Web sessions", "value": "+93%"},
        ],
        "gallery": [
            "https://images.pexels.com/photos/18613224/pexels-photo-18613224.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=900&w=1600",
        ],
    },
    {
        "id": "verte-residences",
        "title": "Verte Residences",
        "category": "Luxury Real Estate · Growth",
        "year": "2023",
        "cover": "https://images.pexels.com/photos/18613224/pexels-photo-18613224.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=900&w=1600",
        "size": "small",
        "order": 6,
        "summary": "Selling a limited collection of architectural residences to a discerning, hard-to-reach audience.",
        "services": ["Paid Marketing", "Website Development"],
        "scope": "An invitation-only digital experience paired with hyper-targeted demand generation for HNI buyers.",
        "results": [
            {"label": "Qualified leads", "value": "640"},
            {"label": "Inventory sold", "value": "84%"},
            {"label": "Cost / qualified lead", "value": "-38%"},
        ],
        "gallery": [
            "https://images.unsplash.com/photo-1488972685288-c3fd157d7c7a?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        ],
    },
    {
        "id": "contiprove",
        "title": "Contiprove",
        "category": "Professional · Website & Brand",
        "year": "2023",
        "cover": "https://images.unsplash.com/photo-1549294413-26f195200c16?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "size": "large",
        "order": 7,
        "summary": "A credible, conversion-ready website and brand system for a global learning & excellence company.",
        "services": ["Website Development", "Brand & Growth Marketing"],
        "scope": "We rebuilt the brand and website to communicate authority, simplify the offering and turn visitors into enrolled learners.",
        "results": [
            {"label": "Enquiry rate", "value": "+148%"},
            {"label": "Page speed", "value": "97/100"},
            {"label": "Bounce rate", "value": "-31%"},
        ],
        "gallery": [
            "https://images.unsplash.com/photo-1488972685288-c3fd157d7c7a?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        ],
    },
    {
        "id": "the-royal-cellar",
        "title": "The Royal Cellar",
        "category": "Lifestyle · Social & Paid",
        "year": "2023",
        "cover": "https://images.unsplash.com/photo-1663530761401-15eefb544889?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "size": "small",
        "order": 8,
        "summary": "A premium F&B membership concept brought to life through cinematic content and precision paid media.",
        "services": ["Social Media Management", "Paid Marketing"],
        "scope": "We built an aspirational membership funnel — cinematic social storytelling feeding a high-intent paid acquisition engine.",
        "results": [
            {"label": "Members acquired", "value": "1,250"},
            {"label": "CPA", "value": "-46%"},
            {"label": "Retention (90d)", "value": "78%"},
        ],
        "gallery": [
            "https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        ],
    },
]
